# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sanath.shetty/PycharmProjects/rbhus_clone/ui_files/admin_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 207)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.messageLabel = QtWidgets.QLabel(self.groupBox)
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_2.addWidget(self.messageLabel, 2, 0, 1, 3)
        self.userBox = QtWidgets.QComboBox(self.groupBox)
        self.userBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.userBox.setObjectName("userBox")
        self.gridLayout_2.addWidget(self.userBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 3)
        self.makeAdminButt = QtWidgets.QPushButton(self.groupBox)
        self.makeAdminButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.makeAdminButt.setObjectName("makeAdminButt")
        self.gridLayout_2.addWidget(self.makeAdminButt, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Admin Tools"))
        self.makeAdminButt.setText(_translate("Form", "Make Admin"))
        self.label.setText(_translate("Form", "User:"))
