# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sanath.shetty/PycharmProjects/rbhus_clone/ui_files/edit_asset.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(445, 201)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.currUserBox = QtWidgets.QLineEdit(self.groupBox)
        self.currUserBox.setReadOnly(True)
        self.currUserBox.setObjectName("currUserBox")
        self.gridLayout_2.addWidget(self.currUserBox, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 2)
        self.newUserBox = QtWidgets.QComboBox(self.groupBox)
        self.newUserBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newUserBox.setObjectName("newUserBox")
        self.gridLayout_2.addWidget(self.newUserBox, 2, 1, 1, 2)
        self.assignButt = QtWidgets.QPushButton(self.groupBox)
        self.assignButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.assignButt.setObjectName("assignButt")
        self.gridLayout_2.addWidget(self.assignButt, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.assetBox = QtWidgets.QLineEdit(self.groupBox)
        self.assetBox.setReadOnly(True)
        self.assetBox.setObjectName("assetBox")
        self.gridLayout_2.addWidget(self.assetBox, 0, 1, 1, 2)
        self.messageLabel = QtWidgets.QLabel(self.groupBox)
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_2.addWidget(self.messageLabel, 4, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Edit"))
        self.label_3.setText(_translate("Form", "Asset:"))
        self.label_2.setText(_translate("Form", "Current User:"))
        self.assignButt.setText(_translate("Form", "Assign"))
        self.label.setText(_translate("Form", "New User:"))
