# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sanath.shetty/PycharmProjects/rbhus_clone/ui_files/new_project_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(445, 380)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.assetFrame = QtWidgets.QFrame(self.groupBox)
        self.assetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.assetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.assetFrame.setObjectName("assetFrame")
        self.gridLayout.addWidget(self.assetFrame, 3, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.audioFileBox = QtWidgets.QLineEdit(self.groupBox)
        self.audioFileBox.setObjectName("audioFileBox")
        self.horizontalLayout_4.addWidget(self.audioFileBox)
        self.selectAudioButt = QtWidgets.QPushButton(self.groupBox)
        self.selectAudioButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectAudioButt.setObjectName("selectAudioButt")
        self.horizontalLayout_4.addWidget(self.selectAudioButt)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nameBox = QtWidgets.QLineEdit(self.groupBox)
        self.nameBox.setObjectName("nameBox")
        self.horizontalLayout.addWidget(self.nameBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.messageLabel = QtWidgets.QLabel(self.groupBox)
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 6, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.createButt = QtWidgets.QPushButton(self.groupBox)
        self.createButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createButt.setObjectName("createButt")
        self.horizontalLayout_2.addWidget(self.createButt)
        self.gridLayout.addLayout(self.horizontalLayout_2, 9, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "New Project"))
        self.label_4.setText(_translate("Form", "Audio:"))
        self.selectAudioButt.setText(_translate("Form", "Select"))
        self.label.setText(_translate("Form", "Name:"))
        self.label_2.setText(_translate("Form", "Asset:"))
        self.label_3.setText(_translate("Form", "User:"))
        self.createButt.setText(_translate("Form", "Create"))
