# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sanath.shetty/PycharmProjects/rbhus_clone/ui_files/version_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 525)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.versionsGroupBox = QtWidgets.QGroupBox(Form)
        self.versionsGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.versionsGroupBox.setObjectName("versionsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.versionsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.versionList = QtWidgets.QListWidget(self.versionsGroupBox)
        self.versionList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.versionList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.versionList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.versionList.setFrameShape(QtWidgets.QFrame.Box)
        self.versionList.setObjectName("versionList")
        self.gridLayout.addWidget(self.versionList, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.versionsGroupBox, 1, 0, 1, 1)
        self.filesGroupBox = QtWidgets.QGroupBox(Form)
        self.filesGroupBox.setObjectName("filesGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.filesGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filesList = QtWidgets.QListWidget(self.filesGroupBox)
        self.filesList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filesList.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.filesList.setFrameShape(QtWidgets.QFrame.Box)
        self.filesList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.filesList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.filesList.setIconSize(QtCore.QSize(64, 64))
        self.filesList.setTextElideMode(QtCore.Qt.ElideNone)
        self.filesList.setMovement(QtWidgets.QListView.Static)
        self.filesList.setFlow(QtWidgets.QListView.LeftToRight)
        self.filesList.setProperty("isWrapping", True)
        self.filesList.setResizeMode(QtWidgets.QListView.Adjust)
        self.filesList.setGridSize(QtCore.QSize(128, 128))
        self.filesList.setViewMode(QtWidgets.QListView.IconMode)
        self.filesList.setWordWrap(True)
        self.filesList.setSelectionRectVisible(True)
        self.filesList.setObjectName("filesList")
        self.gridLayout_2.addWidget(self.filesList, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.filesGroupBox, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commitButt = QtWidgets.QPushButton(Form)
        self.commitButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commitButt.setObjectName("commitButt")
        self.horizontalLayout.addWidget(self.commitButt)
        self.pushButt = QtWidgets.QPushButton(Form)
        self.pushButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButt.setObjectName("pushButt")
        self.horizontalLayout.addWidget(self.pushButt)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(Form)
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_3.addWidget(self.messageLabel, 2, 1, 1, 1)
        self.assetName = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.assetName.setFont(font)
        self.assetName.setAlignment(QtCore.Qt.AlignCenter)
        self.assetName.setObjectName("assetName")
        self.gridLayout_3.addWidget(self.assetName, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.versionsGroupBox.setTitle(_translate("Form", "Versions"))
        self.filesGroupBox.setTitle(_translate("Form", "Files"))
        self.commitButt.setText(_translate("Form", "Commit"))
        self.pushButt.setText(_translate("Form", "Push"))
        self.assetName.setText(_translate("Form", "Asset : Name"))
