# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Repos\rbhus_clone\ui_files\version_list_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 588)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.versionsGroupBox = QtWidgets.QGroupBox(Form)
        self.versionsGroupBox.setObjectName("versionsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.versionsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.versionList = QtWidgets.QListWidget(self.versionsGroupBox)
        self.versionList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.versionList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.versionList.setFrameShape(QtWidgets.QFrame.Box)
        self.versionList.setObjectName("versionList")
        self.gridLayout.addWidget(self.versionList, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.versionsGroupBox, 1, 0, 1, 1)
        self.assetName = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.assetName.setFont(font)
        self.assetName.setAlignment(QtCore.Qt.AlignCenter)
        self.assetName.setObjectName("assetName")
        self.gridLayout_2.addWidget(self.assetName, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButt = QtWidgets.QPushButton(Form)
        self.openButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.openButt.setObjectName("openButt")
        self.horizontalLayout.addWidget(self.openButt)
        self.commitButt = QtWidgets.QPushButton(Form)
        self.commitButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commitButt.setObjectName("commitButt")
        self.horizontalLayout.addWidget(self.commitButt)
        self.pushButt = QtWidgets.QPushButton(Form)
        self.pushButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButt.setObjectName("pushButt")
        self.horizontalLayout.addWidget(self.pushButt)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(Form)
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_2.addWidget(self.messageLabel, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.versionsGroupBox.setTitle(_translate("Form", "Versions"))
        self.assetName.setText(_translate("Form", "Asset : Name"))
        self.openButt.setText(_translate("Form", "Open"))
        self.commitButt.setText(_translate("Form", "Commit"))
        self.pushButt.setText(_translate("Form", "Push"))
