# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Repos\rbhus_clone\tests\app_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(695, 421)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.textFrame = QtWidgets.QFrame(Form)
        self.textFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textFrame.setObjectName("textFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.textFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fontBox = QtWidgets.QFontComboBox(self.textFrame)
        self.fontBox.setObjectName("fontBox")
        self.horizontalLayout.addWidget(self.fontBox)
        self.sizeBox = QtWidgets.QSpinBox(self.textFrame)
        self.sizeBox.setProperty("value", 14)
        self.sizeBox.setObjectName("sizeBox")
        self.horizontalLayout.addWidget(self.sizeBox)
        self.boldButt = QtWidgets.QCheckBox(self.textFrame)
        self.boldButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.boldButt.setObjectName("boldButt")
        self.horizontalLayout.addWidget(self.boldButt)
        self.ItalicButt = QtWidgets.QCheckBox(self.textFrame)
        self.ItalicButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ItalicButt.setObjectName("ItalicButt")
        self.horizontalLayout.addWidget(self.ItalicButt)
        self.underlineButt = QtWidgets.QCheckBox(self.textFrame)
        self.underlineButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.underlineButt.setObjectName("underlineButt")
        self.horizontalLayout.addWidget(self.underlineButt)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.textFrame)
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.textFrame, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        self.slider = QtWidgets.QSlider(Form)
        self.slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_2.addWidget(self.slider)
        self.backwardButt = QtWidgets.QPushButton(Form)
        self.backwardButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.backwardButt.setText("")
        self.backwardButt.setObjectName("backwardButt")
        self.horizontalLayout_2.addWidget(self.backwardButt)
        self.forwardButt = QtWidgets.QPushButton(Form)
        self.forwardButt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.forwardButt.setText("")
        self.forwardButt.setObjectName("forwardButt")
        self.horizontalLayout_2.addWidget(self.forwardButt)
        self.volumeSlider = QtWidgets.QSlider(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.boldButt.setText(_translate("Form", "Bold"))
        self.ItalicButt.setText(_translate("Form", "Italic"))
        self.underlineButt.setText(_translate("Form", "Underline"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
